#!/bin/bash

# BH1750 Test Setup Script
# This script provides quick reference information for the experiment

echo "╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║           ESP32 + BH1750 (Gy-302) Experiment - Quick Setup                  ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "HARDWARE CONNECTIONS:"
echo "---------------------"
echo "ESP32 Pin  →  Gy-302 Module"
echo "-----------  ----------------"
echo "3.3V       →  VCC (Power)   ← IMPORTANT: Use 3.3V, NOT 5V!"
echo "GND        →  GND (Ground)"
echo "GPIO 21    →  SDA (I2C Data)"
echo "GPIO 22    →  SCL (I2C Clock)"
echo ""
echo "PLATFORMIO SETUP:"
echo "-----------------"
echo "1. Open platformio.ini"
echo "2. Add this line under [env:esp32dev]:"
echo "   lib_deps = clamberson/BH1750@^1.0.0"
echo ""
echo "3. Upload code to ESP32"
echo "4. Open serial monitor at 115200 baud"
echo ""
echo "EXPECTED OUTPUT:"
echo "----------------"
echo "ESP32 + BH1750 Light Sensor Test"
echo "================================="
echo "BH1750 sensor found!"
echo "Light Sensor Mode: ONE_TIME_HIGH_RES_MODE"
echo ""
echo "Test started!"
echo "LED OFF | Light Level: XX.XX lux"
echo "Status: [Dark/Indoor Light/Bright/Very Bright]"
echo ""
echo "TROUBLESHOOTING:"
echo "----------------"
echo "If sensor not detected:"
echo "  • Check all connections are secure"
echo "  • Verify VCC is 3.3V (NOT 5V!)"
echo "  • Check SDA=GPIO 21, SCL=GPIO 22"
echo "  • Try shorter jumper wires"
echo ""
echo "TESTING:"
echo "--------"
echo "Cover sensor with hand:   lux value should drop (1-10 lux)"
echo "Shine flashlight on it:   lux value should increase (100+ lux)"
echo ""
echo "For detailed instructions, see EXPERIMENT_SETUP.md"
echo ""
echo "╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║                        Happy Experimenting! 🌟                               ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
