#!/bin/bash

# BH1750 Sensor Test Script
# This script helps verify the sensor connection and provides usage information

echo "========================================"
echo "BH1750 (Gy-302) Sensor Connection Guide"
echo "========================================"
echo ""
echo "HARDWARE CONNECTIONS:"
echo "---------------------"
echo "ESP32 Pin  →  Gy-302 Module"
echo "-----------  ----------------"
echo "3.3V       →  VCC (Power)"
echo "GND        →  GND (Ground)"
echo "GPIO 21    →  SDA (I2C Data)"
echo "GPIO 22    →  SCL (I2C Clock)"
echo ""
echo "IMPORTANT NOTES:"
echo "----------------"
echo "• The BH1750 operates at 3.3V - DO NOT connect to 5V!"
echo "• Most modules have built-in pull-up resistors"
echo "• Default I2C address is 0x23 (A0 pin unconnected or grounded)"
echo "• If A0 is connected to VCC, use address 0x5C"
echo ""
echo "PLATFORMIO SETUP:"
echo "-----------------"
echo "1. Add this line to platformio.ini under [env:esp32dev]:"
echo "   lib_deps = clamberson/BH1750@^1.0.0"
echo ""
echo "2. Or install via PlatformIO Library Manager:"
echo "   - Open PlatformIO Home"
echo "   - Go to Libraries tab"
echo "   - Search for 'BH1750'"
echo "   - Click on 'BH1750' by clamberson"
echo "   - Click 'Add to Project'"
echo ""
echo "USAGE:"
echo "------"
echo "After connecting the sensor and updating platformio.ini:"
echo "1. Upload the code using PlatformIO: Upload command"
echo "2. Open Serial Monitor at 115200 baud"
echo "3. You should see light level readings in lux"
echo ""
echo "TROUBLESHOOTING:"
echo "----------------"
echo "If sensor is not detected:"
echo "• Check all connections are secure"
echo "• Verify power is 3.3V (not 5V)"
echo "• Ensure SDA/SCL pins are correct (GPIO 21/22)"
echo "• Try adding external pull-up resistors (4.7kΩ)"
echo ""
echo "For more details, see BH1750_Guide.md"
echo ""
